# Generated by Django 3.2.6 on 2021-08-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_article_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='gallery',
        ),
    ]
